### ISSUE TITLE
Problem with Wheel Group - Measurement is off

### ISSUE THREAD

**Issue by hazeydavey** [ArkeinGuardia/Triumph_TTS#125]
Wheeling a group shows 5MU when it is only wheeling 4MU.  Please check and see if this is a systemic problem with wheeling now.  Thanks!

![image](https://user-images.githubusercontent.com/81864791/117673416-c8eb7c80-b178-11eb-918c-7f285583a392.png)

**Comment by hazeydavey** [comment]
I did some other testing with different distances and messing with the slider bar on the right to make sure it still happened when set to 0MU and the answer is yes.  When I was using the wheel group to move a 20mm deep stand until it displayed that it would move 1MU, it was only actually moving about .8MU

**Comment by marcpawl** [comment]
fixed.  Mixup in units inches and MU
