### ISSUE TITLE
Make General Acts twice

### ISSUE THREAD

**Issue by ArkeinGuardia** [ArkeinGuardia/Triumph_TTS#13]
We should avoid this. Once you click Make General, or if the base is already a General, it should stop showing that option.

**Comment by marcpawl** [comment]
commit ea29000987dd915ea726132d592feb95d9995a61 (HEAD -> armies3, origin/armies3)
Author: Marc Pawlowsky <marcpawl@gmail.com>
Date:   Fri Apr 9 19:54:00 2021 -0400

    Remove extra space when checking base name to see if base is a general
    Make General Acts twice #13

commit 2fb452fb5c41a28572699d6620106d10bac212f2
Author: Marc Pawlowsky <marcpawl@gmail.com>
Date:   Fri Apr 9 19:51:19 2021 -0400

    Make General Acts twice #13

    check if a base is already general and then do not make it
    a general again.

**Comment by marcpawl** [comment]
fixed
