### ISSUE TITLE
stop rolling my dice

### ISSUE THREAD

**Issue by marcpawl** [ArkeinGuardia/Triumph_TTS#17]
prevent red player from rolling the blue dice, it is confusing me

**Comment by ArkeinGuardia** [comment]
Not working correctly.

The numbers of the other player dissapear, but not the button.

When the numbers dissapear I still can hit the Roll button.

Upon changing players, both numbers dissapear, but the buttons are still there. Tried from both players colors.

![imagen](https://user-images.githubusercontent.com/64328792/116809724-c3ba7c00-ab3f-11eb-9825-89ffb85c1e62.png)

**Comment by ArkeinGuardia** [comment]
Working
