### ISSUE TITLE
Third Label for Armies.

### ISSUE THREAD

**Issue by ArkeinGuardia** [ArkeinGuardia/Triumph_TTS#22]
When I include new armies it is a problem to decide which name is the best. So far we should include a third label for the armies so the second one, the name, will match MeshWesh while the third can be the army itself in all the variants.

Example:

-Classical (Generic theme, like DBA book)
---Hannibal in Italy (MeshWesh match)
-----218-217 BC (variants after applying restrictions)
-----216-203 BC
---Antigonid 
-----320 BC to 285 BC
-----Antigonos from 320 to 301 BC
-----Demetrios from 315 to 285 BC

**Comment by marcpawl** [comment]
Done we have years
