### ISSUE TITLE
Randomize the terrain cards when deploying an army

### ISSUE THREAD

**Issue by ArkeinGuardia** [ArkeinGuardia/Triumph_TTS#25]
Instead of doing it manually they should spawn randomized.

**Comment by ArkeinGuardia** [comment]
What about doing this with all the terrain bags? so each time a player takes the first terrain piece, which is usually what they do, they will have a different one each game.

**Comment by ArkeinGuardia** [comment]
Its not, just a TTS object. Not defined in the code.

**Comment by marcpawl** [comment]
212caad  cards are randomized when game is loaded
