### ISSUE TITLE
Renaming orders

### ISSUE THREAD

**Issue by ArkeinGuardia** [ArkeinGuardia/Triumph_TTS#31]
Rename Push Back to "Fall Back"
Rename "Push Forward" to "Pursue"

**Comment by marcpawl** [comment]
commit d3b61cdcb55ed22677e1ba1ee91ef6704a410b11 (HEAD -> armies3)
Author: Marc Pawlowsky <marcpawl@gmail.com>
Date:   Fri Apr 9 19:37:07 2021 -0400

    Renaming orders #31
    Rename Push Back to "Fall Back"
    Rename "Push Forward" to "Pursue"

**Comment by marcpawl** [comment]
done
