### ISSUE TITLE
unlock table

### ISSUE THREAD

**Issue by marcpawl** [ArkeinGuardia/Triumph_TTS#36]
Since there is now way to unlock the table, might as well remove the menu item once the table is locked.

**Comment by ArkeinGuardia** [comment]
We need un Unlock option

**Comment by marcpawl** [comment]
you cannot just unlock the table as buildings will remain behind, and the items that are attached will remain on the table.

**Comment by ArkeinGuardia** [comment]
In that case I'd leave the Lock button just in case. If there were any mistake and players have to add any extra terrain piece, that would be a problem.

**Comment by marcpawl** [comment]
with the wizard there is no need for unlock anymore.  There is no lock option.

**Comment by marcpawl** [comment]
button removed in 2.2 alpha
