### ISSUE TITLE
Stand Color Highlighting for Grand Triumph!

### ISSUE THREAD

**Issue by hazeydavey** [ArkeinGuardia/Triumph_TTS#43]
The highlighting is great and would work very well for the commands in Grand Triumph!  Color coordinated with the appropriate dice.  However, when saving a game the highlighting is lost.  This means it is not possible to build an army and save it in advance, at least if you plan to use the highlighting.

**Comment by marcpawl** [comment]
reproduced

**Comment by marcpawl** [comment]
fixed 64ab96003476d3fec760bd8503e99d344a2b32a3
