### ISSUE TITLE
Killed right click option does not read blue player

### ISSUE THREAD

**Issue by ArkeinGuardia** [ArkeinGuardia/Triumph_TTS#53]

**Comment by marcpawl** [comment]
commit 4309f5556a20be37fd47e3bd4aa61055af158a1b (HEAD -> armies3, origin/armies3)
Author: Marc Pawlowsky <marcpawl@gmail.com>
Date:   Fri Apr 9 15:17:10 2021 -0400

    Fix loss of RED/BLUE for bases on save.

    Bases were losing the decorations when game was being saved.
    Have explicit decoration for the base player color to make
    it easy to determine.

**Comment by marcpawl** [comment]
done
