### ISSUE TITLE
ALT key magnification objects too dark

### ISSUE THREAD

**Issue by marcpawl** [ArkeinGuardia/Triumph_TTS#59]
Also occurs in DBA.

Put the hand over an object, and hit the ALT key, you should get a magnification of the object.
The objects are very very dark.

Other mods including the sandbox, the objects are not dark.

**Comment by marcpawl** [comment]
Options/Lighting/Ambient Light makes the problem go away.  
We need an artist to adjust the lighting level.

@ArkeinGuardia  can you take a look.  Looks like low hanging fruit for Beta.

**Comment by ArkeinGuardia** [comment]
It was changed originally by Leberecht on the first version of DBA. The ambient light was changed and he placed several light sources, 4 of them, one on each corner. We can change that but the ambient light would change and it looks nice now, although I agree that the ALT option es not good.

I will take a look

**Comment by marcpawl** [comment]
This is the only light code I can find, so we should be able to just take it out and adjust the lighting.

function make_scenery_non_interactable()
    -- Main table
    getObjectFromGUID('558717').interactable = false

    -- Chairs
    getObjectFromGUID('e149a5').interactable = false
    getObjectFromGUID('daff99').interactable = false

    -- Floor
    getObjectFromGUID('83a7b8').interactable = false

    -- Walls
    getObjectFromGUID('77e020').interactable = false
    getObjectFromGUID('6880f1').interactable = false
    getObjectFromGUID('a2475b').interactable = false
    getObjectFromGUID('0d0857').interactable = false

    -- Main point light
    getObjectFromGUID('c0f8eb').interactable = false

    -- Key light
    getObjectFromGUID('4a9adf').interactable = false

    -- Back lights
    getObjectFromGUID('3b5c97').interactable = false
    getObjectFromGUID('018fac').interactable = false

    -- Top light for shadows
    getObjectFromGUID('bc09bc').interactable = false
end

**Comment by ArkeinGuardia** [comment]
Done
