### ISSUE TITLE
Loose model broken

### ISSUE THREAD

**Issue by marcpawl** [ArkeinGuardia/Triumph_TTS#64]

**Comment by marcpawl** [comment]
it is working, but the numbers are very small.  We would need a bounding box on the figures to tell us how much we can move.  The BB could be a fixed size, e.g. 10mm as default with the model having an override.  Something like how trees are handled.  The we could get some real nice randomness, like having all of them bunched together in a corner

**Comment by ArkeinGuardia** [comment]
The movement is good with 10mm I think, maybe it can be a bit more. But it should rotate a bit too.

**Comment by marcpawl** [comment]
fixed in 2.2 alpha
