### ISSUE TITLE
Edited: Fortified and Pack Trains Camp - They should have those terms on the name

### ISSUE THREAD

**Issue by hazeydavey** [ArkeinGuardia/Triumph_TTS#79]
In the previous version of the mod, I really liked being able to drag the Battle Card tokens on to the Army builder mat and have it count the 1 point toward the army build.   It appears that in the beta version the fortified camp token no longer has a point cost.

**Comment by ArkeinGuardia** [comment]
The tokens should be removed, although there are actual bases for fortified camp. They should worth 9 points on the Death counter and 1 point on the army builder

**Comment by ArkeinGuardia** [comment]
Okey, I see the code has it, it counts "Fortified" as +1 if it is an actual camp, but I see that Fortified Camps and Pack Trains camps are not named like that, just "Camp", maybe we should see that too.

**Comment by hazeydavey** [comment]
Oops...   I was probably building on the death mat!  If it counts differently on the builder mat, then that could have caused my confusion.

**Comment by ArkeinGuardia** [comment]
No, no, you are correct. Right now the Token is not being counted because it is not a proper base. And the Fortified Camp does not have either texture or the right term on the name. It is a bug we must change ASAP

**Comment by marcpawl** [comment]
In  function get_plain_model_tile_name(base_definition)
check the base defintion to see if the troop_type is camp, and if there are special attributes for fortified or pack train and return the correct model.

**Comment by marcpawl** [comment]
The calculation of army points and victory points has to be redone and is a work in progress

**Comment by ArkeinGuardia** [comment]
Good, great.

**Comment by marcpawl** [comment]
Let's close this and open two items,  Rework army point calculations, and rework casualty point calculations.
